spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        use_sql_comments: true
        show_sql: false
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://linkit-dev.cbew06km0jxq.ap-northeast-1.rds.amazonaws.com:3306/linkit_dev_db
    username: linkit_root
    password: fldpwhdfldzlt!
    driver-class-name: com.mysql.cj.jdbc.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
